15s

diff --git a/.github/workflows/my-ci-pipeline.yml b/.github/workflows/my-ci-pipeline.yml
--- a/.github/workflows/my-ci-pipeline.yml
+++ b/.github/workflows/my-ci-pipeline.yml
@@ -57,33 +57,33 @@ jobs:
           docker compose up -d
           docker ps --filter "name=backend" --filter "name=frontend" --filter "name=db"
 
-      - name: Keep it simple
+      - name: Health from backend container itself (after sleeping 15s)
         run: |
           sleep 15
           docker ps
           docker exec backend curl -s http://localhost:8082/health
 
-      - name: Keep it simple - host
-        run: |
-          docker ps
-          curl -s http://localhost:8082/health
-
+#      - name: Health from the host machine
+#        run: |
+#          docker ps
+#          curl -s http://localhost:8082/health
+#
+#      - name: Verify backend health endpoint
+#        run: |
+#          for i in {1..10}; do
+#            docker exec backend curl -s http://localhost:8082/health
+#            if docker exec backend curl -s http://localhost:8082/health | grep -q '"status":"UP"'; then
+#              echo "Backend health is OK"
+#              exit 0
+#            else
+#              echo "Waiting for backend to be healthy..."
+#              sleep 3
+#            fi
+#          done
+#          echo "Backend health check failed"
+#          exit 1
+#
       - name: Verify backend health endpoint
         run: |
-          for i in {1..10}; do
-            docker exec backend curl -s http://localhost:8082/health
-            if docker exec backend curl -s http://localhost:8082/health | grep -q '"status":"UP"'; then
-              echo "Backend health is OK"
-              exit 0
-            else
-              echo "Waiting for backend to be healthy..."
-              sleep 3
-            fi
-          done
-          echo "Backend health check failed"
-          exit 1
-
-      - name: Verify backend health endpoint
-        run: |
           curl -s http://localhost:8082/health
-          curl -s http://localhost:8082/health | grep -q '"status":"UP"'
+          curl -s http://localhost:8082/health | grep -q '"status":"xUP"'
